services:
  trace:
    image: trace
    build:
      context: .
      target: tracer
    restart: unless-stopped
    stdin_open: true
    network_mode: host
    tty: true
    cap_add:
      - NET_RAW
      - NET_ADMIN
    volumes:
      - /traces:/traces
#    environment:
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "5"


